version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/RP.Dashboard.API/RP.Dashboard.API.csproj --verbosity m
build_script:
  - cmd: dotnet build ./src/RP.Dashboard.API/RP.Dashboard.API.csproj
after_build:
  # For once the build has completed
artifacts:
  # For once the build has completed
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/RP.Dashboard.API.Tests/RP.Dashboard.API.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd src
  - cmd: cd RP.Dashboard.API.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off
